'videos_root_folder': '/home/anton/work/fitMate/datasets/squats_non_compound'
'videos_source_subfolder': 'split squat'
'videos_target_subfolder': 'split squat_steady_camera'
'move_to_folders_strategy': 'do_not_sort'  # 'by_source_filename'
'videos_extensions': ['.mp4', '.MP4', '.mkv', '.webm']
'use_multiprocessing': True
'number_processes': 2