database:
  'folder': '/home/anton/work/fitMate/datasets'
  'filename': 'youtube_rep_fit_database.db'

video_chapters_promts:
  'folder': '/home/anton/work/fitMate/datasets/exercises_filter_promts'
  'filename': 'squats_non_compound_chapters.json'

videos_promts:
  'folder': '/home/anton/work/fitMate/datasets/exercises_filter_promts'
  'filename': 'squats_short_videos.json'

output:
  'chapters_output_folder': '/home/anton/work/fitMate/datasets/squats_non_compound'
  'videos_output_folder': '/home/anton/work/fitMate/datasets/squats_short_videos'

