from filters.steady_camera_filter.core.persons_mask.persons_mask_factory import PersonsMaskFactory
from filters.steady_camera_filter.core.persons_mask.persons_mask_yolo_detector import PersonsMaskYoloDetector, create_yolo_detector_instance
from filters.steady_camera_filter.core.persons_mask.persons_mask_yolo_segmentation import PersonsMaskYoloSegmentation, create_yolo_segmentation_instance

factory = PersonsMaskFactory()

factory.register_builder(PersonsMaskYoloDetector.alias, create_yolo_detector_instance)
factory.register_builder(PersonsMaskYoloSegmentation.alias, create_yolo_segmentation_instance)
